import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Eye, FileText } from 'lucide-react';
import { generateDetailedReports, DetailedReport } from '../../lib/mockData';
import ReportViewer from '../../components/dashboard/ReportViewer';

const Reports: React.FC = () => {
  const reports = generateDetailedReports();
  const [selectedReport, setSelectedReport] = useState<DetailedReport | null>(null);
  const [isViewerOpen, setIsViewerOpen] = useState(false);

  const handleViewReport = (report: DetailedReport) => {
    setSelectedReport(report);
    setIsViewerOpen(true);
  };

  const handleCloseViewer = () => {
    setIsViewerOpen(false);
    setSelectedReport(null);
  };

  return (
    <>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <h1 className="text-3xl font-bold text-gray-800 dark:text-white mb-2">Your Health Reports</h1>
        <p className="text-gray-600 dark:text-gray-300 mb-8">
          Review your weekly and monthly health reports generated by Chronic AI.
        </p>
        
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead className="bg-gray-50 dark:bg-gray-700/50">
                <tr>
                  <th className="p-4 font-semibold text-gray-600 dark:text-gray-300">Report Name</th>
                  <th className="p-4 font-semibold text-gray-600 dark:text-gray-300">Date</th>
                  <th className="p-4 font-semibold text-gray-600 dark:text-gray-300">Type</th>
                  <th className="p-4 font-semibold text-gray-600 dark:text-gray-300 text-right">Action</th>
                </tr>
              </thead>
              <tbody>
                {reports.map((report, index) => (
                  <motion.tr
                    key={report.id}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.1 * index }}
                    className="border-b border-gray-200 dark:border-gray-700"
                  >
                    <td className="p-4 flex items-center">
                      <FileText className="w-5 h-5 mr-3 text-brand-primary flex-shrink-0" />
                      <span className="font-medium text-gray-800 dark:text-gray-100">{report.name}</span>
                    </td>
                    <td className="p-4 text-gray-600 dark:text-gray-400">{report.date}</td>
                    <td className="p-4">
                      <span className="px-3 py-1 text-xs font-semibold rounded-full bg-blue-100 text-blue-800 dark:bg-blue-500/20 dark:text-blue-300">
                        {report.type}
                      </span>
                    </td>
                    <td className="p-4 text-right">
                      <button 
                        onClick={() => handleViewReport(report)}
                        className="p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
                        aria-label="View report"
                      >
                        <Eye className="w-5 h-5 text-gray-500" />
                      </button>
                    </td>
                  </motion.tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </motion.div>

      {selectedReport && (
        <ReportViewer 
          isOpen={isViewerOpen}
          onClose={handleCloseViewer}
          report={selectedReport}
        />
      )}
    </>
  );
};

export default Reports;
