/*
          # Create Health Reports Table
          This migration creates a new table `health_reports` to store patient health data imports and their corresponding AI-generated analysis.

          ## Query Description: 
          - Creates the `health_reports` table with columns for storing raw JSON data, AI-generated summaries, key vitals, and recommendations.
          - Establishes a foreign key relationship to `auth.users` to link reports to specific users.
          - Enables Row Level Security (RLS) to ensure data privacy.
          - Adds RLS policies so that users can only create and view their own reports. This operation is safe and does not affect existing data.

          ## Metadata:
          - Schema-Category: "Structural"
          - Impact-Level: "Low"
          - Requires-Backup: false
          - Reversible: true

          ## Structure Details:
          - Table: `public.health_reports`
          - Columns: `id`, `user_id`, `created_at`, `report_name`, `raw_data`, `ai_summary`, `key_vitals`, `recommendations`

          ## Security Implications:
          - RLS Status: Enabled
          - Policy Changes: Yes (New policies for INSERT and SELECT are added)
          - Auth Requirements: Users must be authenticated to interact with this table.
          
          ## Performance Impact:
          - Indexes: A foreign key index on `user_id` is created, which will improve query performance when fetching reports for a specific user.
          - Triggers: None
          - Estimated Impact: Low performance impact.
          */

-- 1. Create the health_reports table
CREATE TABLE public.health_reports (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamp with time zone not null default now(),
    report_name text not null,
    raw_data jsonb not null,
    ai_summary text,
    key_vitals jsonb,
    recommendations jsonb
);

-- 2. Add comments to the columns for clarity
COMMENT ON TABLE public.health_reports IS 'Stores patient health data imports and AI-generated reports.';
COMMENT ON COLUMN public.health_reports.raw_data IS 'The original JSON data imported by the user.';
COMMENT ON COLUMN public.health_reports.ai_summary IS 'The text summary generated by the AI.';
COMMENT ON COLUMN public.health_reports.key_vitals IS 'Structured key vitals extracted by the AI.';
COMMENT ON COLUMN public.health_reports.recommendations IS 'Actionable recommendations provided by the AI.';

-- 3. Enable Row Level Security on the new table
ALTER TABLE public.health_reports ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies
-- Users can insert a report for themselves
CREATE POLICY "Users can create their own health reports"
ON public.health_reports
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can view their own reports
CREATE POLICY "Users can view their own health reports"
ON public.health_reports
FOR SELECT
USING (auth.uid() = user_id);

-- Users can update their own reports (optional, can be restricted)
CREATE POLICY "Users can update their own health reports"
ON public.health_reports
FOR UPDATE
USING (auth.uid() = user_id);

-- Users can delete their own reports (optional, can be restricted)
CREATE POLICY "Users can delete their own health reports"
ON public.health_reports
FOR DELETE
USING (auth.uid() = user_id);
