/*
          # Create Health Reports Table
          This migration creates the `health_reports` table to store user-imported health data and the corresponding AI-generated analysis. It also enables Row Level Security to ensure users can only access their own data.

          ## Query Description: [This operation creates a new table `health_reports` for storing patient report data. It is a non-destructive structural change and is safe to run on existing databases as it only adds new structures.]
          
          ## Metadata:
          - Schema-Category: "Structural"
          - Impact-Level: "Low"
          - Requires-Backup: false
          - Reversible: true
          
          ## Structure Details:
          - Table: `public.health_reports`
          - Columns: `id`, `user_id`, `created_at`, `report_name`, `raw_data`, `report_data`
          
          ## Security Implications:
          - RLS Status: Enabled
          - Policy Changes: Yes (Adds policies for SELECT and INSERT)
          - Auth Requirements: Users must be authenticated to interact with the table.
          
          ## Performance Impact:
          - Indexes: Adds a primary key index on `id` and a foreign key index on `user_id`.
          - Triggers: None
          - Estimated Impact: Low. This is a standard table creation.
          */

-- Create the table for storing health reports
CREATE TABLE IF NOT EXISTS public.health_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    report_name text NOT NULL,
    raw_data jsonb NOT NULL,
    report_data jsonb NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.health_reports ENABLE ROW LEVEL SECURITY;

-- Drop policies if they exist to ensure a clean slate
DROP POLICY IF EXISTS "Allow users to view their own reports" ON public.health_reports;
DROP POLICY IF EXISTS "Allow users to insert their own reports" ON public.health_reports;

-- Create policies for data access
CREATE POLICY "Allow users to view their own reports"
ON public.health_reports
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow users to insert their own reports"
ON public.health_reports
FOR INSERT WITH CHECK (auth.uid() = user_id);
