-- Create the health_reports table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.health_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add user_id column if it doesn't exist
ALTER TABLE public.health_reports
ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

-- Add raw_data column if it doesn't exist
ALTER TABLE public.health_reports
ADD COLUMN IF NOT EXISTS raw_data JSONB;

-- Add report_data column if it doesn't exist
ALTER TABLE public.health_reports
ADD COLUMN IF NOT EXISTS report_data JSONB;

-- Add report_name column if it doesn't exist
ALTER TABLE public.health_reports
ADD COLUMN IF NOT EXISTS report_name TEXT;

-- Enable Row Level Security on the table
ALTER TABLE public.health_reports ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to ensure a clean slate
DROP POLICY IF EXISTS "Users can insert their own reports" ON public.health_reports;
DROP POLICY IF EXISTS "Users can view their own reports" ON public.health_reports;
DROP POLICY IF EXISTS "Users can update their own reports" ON public.health_reports;
DROP POLICY IF EXISTS "Users can delete their own reports" ON public.health_reports;

-- Create the correct, comprehensive policies
CREATE POLICY "Users can insert their own reports"
ON public.health_reports FOR INSERT
WITH CHECK ( auth.uid() = user_id );

CREATE POLICY "Users can view their own reports"
ON public.health_reports FOR SELECT
USING ( auth.uid() = user_id );

CREATE POLICY "Users can update their own reports"
ON public.health_reports FOR UPDATE
USING ( auth.uid() = user_id );

CREATE POLICY "Users can delete their own reports"
ON public.health_reports FOR DELETE
USING ( auth.uid() = user_id );
